import React, { useState, useEffect } from 'react';
import { useGemini } from '../hooks/useGemini';
import { useTTS } from '../hooks/useTTS';
import { useAuth } from '../hooks/useAuth';
import { supabase } from '../lib/supabase';
import { cn } from '../lib/utils';
import { Copy, Volume2, Sparkles, MessageSquare, Save } from 'lucide-react';

const TABS = [
    { id: 'daily', label: 'Daily' },
    { id: 'weekly', label: 'Weekly' },
    { id: 'monthly', label: 'Monthly' },
    { id: 'stumped', label: 'Stumped' },
    { id: 'ai', label: '✨ Custom', special: true },
] as const;

const CONTEXT_TEXT: Record<string, string> = {
    daily: "<strong>Why this works:</strong> Daily questions should be low-friction. They focus on gratitude, intention, and small wins to build momentum without overwhelming you.",
    weekly: "<strong>Why this works:</strong> Weekly reviews are tactical. They help you zoom out slightly to adjust your course, migrate tasks, and ensure you aren't just 'busy' but effective.",
    monthly: "<strong>Why this works:</strong> Monthly logs are for deep strategy. This is the time to be honest about your trajectory. If a goal isn't working, this is the time to drop it.",
    stumped: "<strong>Why this works:</strong> These prompts break the pattern of perfectionism. By forcing you to observe your surroundings or list simple things, you bypass the 'internal editor' blocking your flow.",
    ai: "<strong>Why this works:</strong> Sometimes standard questions don't fit. The AI Coach analyzes your specific context to ask the <em>one</em> right question that will unlock your thinking."
};

const TITLES: Record<string, string> = {
    daily: "Daily Reflection",
    weekly: "Weekly Review",
    monthly: "Monthly Reset",
    stumped: "Unblock Your Mind",
    ai: "AI Reflection Partner"
};

export const PromptEngine: React.FC = () => {
    const [currentTab, setCurrentTab] = useState<string>('daily');
    const [prompt, setPrompt] = useState<string>('');
    const [aiContext, setAiContext] = useState('');
    const [copyFeedback, setCopyFeedback] = useState(false);

    const [answer, setAnswer] = useState('');
    const [isSaving, setIsSaving] = useState(false);
    const [saveMessage, setSaveMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null);

    const { user } = useAuth();
    
    const { generatePrompt, digDeeper, analyzeSentiment, loading, error } = useGemini();
    const { speak, isSpeaking } = useTTS();

    const handleGenerate = async (tab: string = currentTab) => {
        const text = await generatePrompt(tab, aiContext);
        setPrompt(text);
    };

    const handleDigDeeper = async () => {
        const result = await digDeeper(prompt);
        if (result) setPrompt(result);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(prompt);
        setCopyFeedback(true);
        setTimeout(() => setCopyFeedback(false), 2000);
    };

    const handleSave = async () => {
        if (!user || !prompt || !answer.trim()) return;
        setIsSaving(true);
        setSaveMessage(null);

        try {
            // Analyze sentiment/emotion before saving
            const sentimentResult = await analyzeSentiment(answer);

            const { error } = await supabase.from('entries').insert({
                user_id: user.id,
                prompt_text: prompt,
                response_text: answer,
                category: currentTab,
                sentiment: sentimentResult,
                created_at: new Date().toISOString(),
            });

            if (error) throw error;
            setSaveMessage({ type: 'success', text: 'Entry saved successfully!' });
            setAnswer('');
            setTimeout(() => setSaveMessage(null), 3000);
        } catch (err: unknown) {
             console.error('Error saving entry:', err);
             setSaveMessage({ type: 'error', text: 'Failed to save entry.' });
        } finally {
            setIsSaving(false);
        }
    };

    // Initial load
    useEffect(() => {
        handleGenerate('daily');
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const handleTabChange = (tabId: string) => {
        setCurrentTab(tabId);
        if (tabId === 'ai') {
            setPrompt("Tell me briefly about your day or what's on your mind...");
        } else {
            handleGenerate(tabId);
        }
    };

    return (
        <section id="generator" className="max-w-5xl mx-auto px-4 py-12">
            <div className="bg-white rounded-2xl shadow-sm border border-stone-200 overflow-hidden">
                {/* Engine Context */}
                <div className="p-6 md:p-8 border-b border-stone-100 bg-stone-50/50">
                    <h3 className="text-2xl serif-font mb-2">The Prompt Engine</h3>
                    <p className="text-stone-600">
                        Select a timeframe. Every question is uniquely generated by AI to ensure you never answer the same prompt twice.
                    </p>
                </div>

                {/* Tabs */}
                <div className="flex flex-wrap border-b border-stone-200">
                    {TABS.map((tab) => {
                        const isSpecial = 'special' in tab;
                        return (
                        <button
                            key={tab.id}
                            onClick={() => handleTabChange(tab.id)}
                            className={cn(
                                "flex-1 py-4 px-2 text-center text-sm font-medium border-b-2 transition-colors",
                                currentTab === tab.id 
                                    ? (isSpecial
                                        ? "border-amber-700 bg-amber-100 text-amber-900" 
                                        : "border-stone-800 text-stone-800 bg-stone-50")
                                    : (isSpecial
                                        ? "border-transparent text-amber-700 bg-amber-50/50 hover:bg-amber-100"
                                        : "border-transparent text-stone-500 hover:text-stone-800 hover:bg-stone-50")
                            )}
                        >
                            {tab.label}
                        </button>
                    )})}
                </div>

                {/* Display Area */}
                <div className="p-8 md:p-12 min-h-[350px] flex flex-col items-center justify-center text-center relative bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0IiBoZWlnaHQ9IjQiPgo8cmVjdCB3aWR0aD0iNCIgaGVpZ2h0PSI0IiBmaWxsPSIjZmZmIi8+CjxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9IiNlN2U1ZTQiLz4KPC9zdmc+')]">
                    
                    <div className="mb-6 inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-stone-100 text-stone-600 uppercase tracking-wider">
                        {TITLES[currentTab]}
                    </div>

                    {currentTab === 'ai' && (
                        <div className="w-full max-w-lg mb-6 bg-white p-2 rounded-lg border border-stone-200 shadow-sm">
                            <textarea 
                                value={aiContext}
                                onChange={(e) => setAiContext(e.target.value)}
                                className="w-full p-3 text-stone-700 bg-transparent outline-none resize-none text-sm" 
                                rows={2} 
                                placeholder="Briefly describe your situation (e.g., 'I felt anxious about a meeting' or 'I want to celebrate a win')..."
                            />
                        </div>
                    )}

                    <h4 className={cn(
                        "serif-font mb-8 max-w-2xl leading-snug fade-in transition-all duration-300",
                        currentTab === 'ai' && !prompt.startsWith('"') && !prompt.endsWith('"') && prompt.includes("Tell me") 
                            ? "text-stone-400 italic text-xl" 
                            : "text-stone-800 text-2xl md:text-3xl"
                    )}>
                       {currentTab === 'ai' && !prompt.startsWith('"') ? prompt : `"${prompt.replace(/"/g, '')}"`}
                    </h4>

                    {/* Answer Area */}
                    <div className="w-full max-w-2xl mb-8">
                        <textarea
                            value={answer}
                            onChange={(e) => setAnswer(e.target.value)}
                            placeholder="Type your reflection here..."
                            className="w-full p-4 bg-white/80 border border-stone-200 rounded-lg shadow-inner text-stone-700 focus:ring-2 focus:ring-stone-400 focus:outline-none transition-all placeholder:text-stone-400"
                            rows={4}
                        />
                         {saveMessage && (
                            <div className={cn(
                                "mt-2 text-sm text-center",
                                saveMessage.type === 'success' ? "text-green-600" : "text-red-600"
                            )}>
                                {saveMessage.text}
                            </div>
                        )}
                    </div>

                    <div className="flex flex-col md:flex-row gap-4 flex-wrap justify-center">
                        <button 
                            onClick={() => handleGenerate()}
                            disabled={loading}
                            className={cn(
                                "text-white px-6 py-3 rounded-lg transition-colors flex items-center justify-center gap-2 shadow-lg btn-hover min-w-[160px]",
                                currentTab === 'ai' ? "bg-amber-800 hover:bg-amber-900" : "bg-stone-800 hover:bg-stone-700",
                                loading && "opacity-75 cursor-wait"
                            )}
                        >
                            {loading ? <div className="w-5 h-5 border-2 border-white/30 border-l-white rounded-full animate-spin" /> : <Sparkles className="w-4 h-4" />}
                            <span>{currentTab === 'ai' ? "Ask Gemini" : "Generate New"}</span>
                        </button>

                         <button 
                            onClick={handleSave}
                            disabled={isSaving || !answer.trim()}
                            className={cn(
                                "text-white px-6 py-3 rounded-lg transition-colors flex items-center justify-center gap-2 shadow-lg btn-hover min-w-[140px]",
                                "bg-stone-700 hover:bg-stone-600 disabled:bg-stone-400 disabled:cursor-not-allowed"
                            )}
                        >
                            {isSaving ? <div className="w-4 h-4 border-2 border-white/30 border-l-white rounded-full animate-spin" /> : <Save className="w-4 h-4" />}
                            <span>Save Entry</span>
                        </button>
                        
                        {currentTab !== 'ai' && (
                            <button 
                                onClick={handleDigDeeper}
                                disabled={loading || prompt.includes("Start by")}
                                className="bg-stone-100 border border-stone-200 text-stone-700 px-6 py-3 rounded-lg hover:bg-stone-200 transition-colors flex items-center justify-center gap-2 btn-hover" 
                                title="Ask a follow-up question"
                            >
                                <MessageSquare className="w-4 h-4" />
                                <span>Dig Deeper</span>
                            </button>
                        )}

                        <button 
                            onClick={handleCopy}
                            className="bg-white border border-stone-300 text-stone-700 px-6 py-3 rounded-lg hover:bg-stone-50 transition-colors flex items-center justify-center gap-2 btn-hover"
                        >
                            <Copy className="w-4 h-4" />
                            <span>Copy</span>
                        </button>
                        <button 
                            onClick={() => speak(prompt)}
                            disabled={isSpeaking}
                            className="bg-white border border-stone-300 text-stone-700 px-6 py-3 rounded-lg hover:bg-stone-50 transition-colors flex items-center justify-center gap-2 btn-hover"
                        >
                            <Volume2 className="w-4 h-4" />
                            <span>Listen</span>
                        </button>
                    </div>
                    
                    {error && (
                        <div className="mt-4 text-red-600 text-sm bg-red-50 px-4 py-2 rounded-md">
                            {error}
                        </div>
                    )}

                    <div className={cn(
                        "absolute bottom-4 text-green-600 text-sm transition-opacity duration-300",
                        copyFeedback ? "opacity-100" : "opacity-0"
                    )}>
                        Copied to clipboard!
                    </div>
                </div>

                {/* Sub-Explanation Area */}
                <div 
                    className="bg-stone-100 p-6 text-sm text-stone-600 border-t border-stone-200"
                    dangerouslySetInnerHTML={{ __html: CONTEXT_TEXT[currentTab] }}
                />
            </div>
        </section>
    );
};
